const NEW_YOUTUBE_VIDEO = 'NEW_YOUTUBE_VIDEO';
const NEW_INSTAGRAM_POST = 'NEW_INSTAGRAM_POST';
const NEW_FACEBOOK_POST = 'NEW_FACEBOOK_POST';

module.exports = {
  NEW_YOUTUBE_VIDEO,
  NEW_INSTAGRAM_POST,
  NEW_FACEBOOK_POST,
};
